name: Release new version

env:
  GIT_USERNAME: "DefectDojo release bot"
  GIT_EMAIL: "dojo-release-bot@users.noreply.github.com"
on:
  push:
    tags:
      - '*.*.*'
      - '*.*.*.*'

jobs:
  job-get-tag:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-tag.outputs.tag }}
    steps:
      - id: set-tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
  job-build-and-push:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          docker-image: [django, nginx]
          docker-tag: [latest, ${{ needs.job-get-tag.outputs.tag }}]
      steps:
        - name: Checkout dev branch
          uses: actions/checkout@v2
        - name: Grab repository org name
        - id: set-repo-org
          run: echo ::set-output name=repoorg::${GITHUB_REPOSITORY%%/*}
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push id: docker_build
          env:
            REPO_ORG: ${{ steps.set-repo-org.outputs.repoorg }}
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: $REPO_ORG/defectdojo-${{ matrix.docker-image}}:${{ matrix.docker-tag }}
            file: ./Dockerfile.${{ matrix.docker-image }}
            context: .
        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}
