name: Docker build and push

on:
  push:
    tags:
      - '*.*.*'
      - '*.*.*.*'

jobs:
  job-build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-tag.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo ::set-output name=matrix::[{\"docker-image\":\"django\",\"nginx\"},{\"docker-tag\":\"latest\",\"${GITHUB_REF#refs/*/}\"}]"
        # run: echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
  job-build-and-push:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix: ${{fromJson(needs.job-build-matrix.outputs.matrix)}}
      steps:
        - name: Checkout dev branch
          uses: actions/checkout@v2
        - id: set-repo-org
          run: echo ::set-output name=repoorg::${GITHUB_REPOSITORY%%/*}
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push id: docker_build
          env:
            REPO_ORG: ${{ steps.set-repo-org.outputs.repoorg }}
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: $REPO_ORG/defectdojo-${{ matrix.docker-image}}:${{ matrix.docker-tag }}
            file: ./Dockerfile.${{ matrix.docker-image }}
            context: .
        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}
