name: Release new version

on:
  workflow_dispatch:
    inputs:
      release_number:
        description: 'Release version (x.y.z format)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v2
        with:
          ref: dev
        # - name: Create new release branch
        # uses: peterjgrainger/action-create-branch@2.0.1
        # env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #with:
        #  branch: release/${{ github.event.inputs.release_number }}
      - name: Create release branch
        run: |
          echo "NEW_BRANCH=release/${{ github.event.inputs.release_number }}" >> $GITHUB_ENV
      - name: Configure git
        run: |
          git config --global user.name "Dojo release bot"
          git config --global user.email "dojo-release-bot@users.noreply.github.com"
      - name: Push branch
        run: git push origin HEAD:${NEW_BRANCH}
      - name: Checkout release branch
        uses: actions/checkout@v2
        with:
          ref: release/${{ github.event.inputs.release_number }}
      - name: Update version numbers in key files
        run: |
          # sed -ri "s/'([0-9]+(\.[0-9]+)*)'/'${{ github.event.inputs.release_number }}'/" dojo/__init__.py
          sed -ri "s/__version__ = '.*'/__version__ = '${{ github.event.inputs.release_number }}'/" dojo/__init__.py
          # sed -ri "s/'([0-9]+(\.[0-9]+)*)'/'${{ github.event.inputs.release_number }}'/" setup.py
          sed -ri "s/version='.*'/version='${{ github.event.inputs.release_number }}'/" setup.py
          sed -ri "s/appVersion: \"([0-9]+(\.[0-9]+)*)\"/appVersion: \"${{ github.event.inputs.release_number }}\"/" helm/defectdojo/Chart.yaml
      - name: Check numbers
        run: |
          grep version dojo/__init__.py
          grep version setup.py
          grep appVersion helm/defectdojo/Chart.yaml
      - name: Push version changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_user_name: "dojo_bot"
          commit_user_email: "noreply@defectdojo.org"
          commit_author: "Dojo Bot <noreply@defectdojo.org>"
          commit_message: "Update versions"
          branch: ${{ github.head_ref }}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
