name: Release new version

on:
  workflow_dispatch:
    inputs:
      release_number:
        description: 'Release version (x.y.z format)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master
      - run: |
          echo "This is release ${{ github.event.inputs.release_number }}"
      - name: Create new release branch
        uses: peterjgrainger/action-create-branch@2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ github.event.inputs.release_number }}
      - name: Update version numbers in key files
        run: |
            sed -ir "s/'([0-9]+(\.[0-9]+)*)'/'${{ github.event.inputs.release_number }}'/" dojo/__init.py__
            sed -ir "s/'([0-9]+(\.[0-9]+)*)'/'${{ github.event.inputs.release_number }}'/" setup.py
            sed -ir "s/appVersion: \"([0-9]+(\.[0-9]+)*)\"/appVersion: \"${{ github.event.inputs.release_number }}\"/" helm/defectdojo/Chart.yaml
      - name: Check numbers
        run: |
            grep version dojo/__init.py__
            grep version setup.py
            grep appVersion helm/defectdojo/Chart.yaml
